In [39]:
import numpy as np

np_2d_array = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])
print(np_2d_array)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]
 [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
  50]]


In [40]:
#From the second element, slice elements from index 1 to index 4 (not included):
print('From the second element, slice elements from index 1 to index 4 (not included): ', np_2d_array[1, 1:4])

From the second element, slice elements from index 1 to index 4 (not included):  [27 28 29]


In [41]:
#From both elements, slice index 1 to index 4 (not included)
print('From both elements, slice index 1 to index 4 (not included): ',np_2d_array[0:, 1:4])

From both elements, slice index 1 to index 4 (not included):  [[ 2  3  4]
 [27 28 29]]


In [42]:
#Single Row
print('Single Row -> First Row Value:  ', np_2d_array[0])

Single Row -> First Row Value:   [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [43]:
#First Column
print('First Column: ', [row[0] for row in np_2d_array])

First Column:  [1, 26]


In [44]:
#Top Left 2x3 Submatrix - Sample 1
print('Top Left 2x3 Submatrix: ', np_2d_array[:, :3])
#Top Left 2x3 Submatrix - Sample 2
submatrix_2x5 = [row[:5] for row in np_2d_array[:2]]
print('Top Left 2x5 Submatrix: ', submatrix_2x5)

Top Left 2x3 Submatrix:  [[ 1  2  3]
 [26 27 28]]
Top Left 2x5 Submatrix:  [array([1, 2, 3, 4, 5]), array([26, 27, 28, 29, 30])]


In [45]:
#Bottom Right 2x3 Submatrix
print('Bottom Right 2x3 Submatrix: ', np_2d_array[:, -3:])
#Bottom Right 2x5 Submatrix
print('Bottom Right 2x5 Submatrix: ', [row[-5:] for row in np_2d_array[:2]])

Bottom Right 2x3 Submatrix:  [[23 24 25]
 [48 49 50]]
Bottom Right 2x5 Submatrix:  [array([21, 22, 23, 24, 25]), array([46, 47, 48, 49, 50])]


In [46]:
# Slicing a Range of Rows and Columns
# First Row, First Three Columns
print('First Row, First Three Columns: ', np_2d_array[0][:3])

#Second Row, Last Four Columns
print('Second Row, Last Four Columns: ', np_2d_array[1][-4:])

First Row, First Three Columns:  [1 2 3]
Second Row, Last Four Columns:  [47 48 49 50]


In [47]:
#Every Second Element from First Row
print('Every Second Element from First Row: ', np_2d_array[0][::2])

Every Second Element from First Row:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [48]:
#Every Second Element from Both Rows:
print('Every Second Element from Both Rows: ', [row[::2] for row in np_2d_array])

Every Second Element from Both Rows:  [array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25]), array([26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])]


In [49]:
#Find even elements from both rows
print('Find even elements from both rows: ', [np_2d_array[np_2d_array%2 == 0]])

Find even elements from both rows:  [array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])]
