In [10]:
import numpy as np

In [11]:
"""Iterating Over a 1D Array"""

# Define a 1D array
arr_1d = np.array([10, 20, 30, 40, 50])

print("Iterating over a 1D array:")
for value in arr_1d:
    print(value)

Iterating over a 1D array:
10
20
30
40
50


In [12]:
"""Iterating Over a 2D Array (Row-wise)"""
# Define a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("\nIterating over a 2D array (row-wise):")
for row in arr_2d:
    print(row)


Iterating over a 2D array (row-wise):
[1 2 3]
[4 5 6]
[7 8 9]


In [13]:
"""Iterating Over a 2D Array (Element-wise)"""
# Define a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("\nIterating over a 2D array (element-wise):")
for row in arr_2d:
    for element in row:
        print(element)


Iterating over a 2D array (element-wise):
1
2
3
4
5
6
7
8
9


In [14]:
"""Iterating Over a 2D Array Using np.nditer"""
# Define a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nIterating over a 2D array using np.nditer:")
for element in np.nditer(arr_2d):
    print(element)


Iterating over a 2D array using np.nditer:
1
2
3
4
5
6
7
8
9


In [15]:
"""Iterating with Indices"""

# Define a 1D array
arr_1d = np.array([10, 20, 30, 40, 50])

print("\nIterating with indices:")
for index, value in enumerate(arr_1d):
    print(f"Index {index}: Value {value}")


Iterating with indices:
Index 0: Value 10
Index 1: Value 20
Index 2: Value 30
Index 3: Value 40
Index 4: Value 50


In [16]:
""" Iterating Over a 2D Array Using np.ndenumerate"""
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nIterating over a 2D array using np.ndenumerate:")
for index, value in np.ndenumerate(arr_2d):
    print(f"Index {index}: Value {value}")
    


Iterating over a 2D array using np.ndenumerate:
Index (0, 0): Value 1
Index (0, 1): Value 2
Index (0, 2): Value 3
Index (1, 0): Value 4
Index (1, 1): Value 5
Index (1, 2): Value 6
Index (2, 0): Value 7
Index (2, 1): Value 8
Index (2, 2): Value 9


In [17]:
"""Iterating Over a 3D Array"""
arr_3d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nIterating over a 3D array using np.ndenumerate:")
for arr_2d in arr_3d:
    for row in arr_2d:
        print(row)
    



Iterating over a 3D array using np.ndenumerate:
1
2
3
4
5
6
7
8
9


In [18]:
"""Using List Comprehensions for Iteration"""
# Define a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Create a new array with squared values
squared_values = np.array([x**2 for x in arr_1d])

print("\nSquared values using list comprehension:")
print(squared_values)


Squared values using list comprehension:
[ 1  4  9 16 25]
