In [24]:
import numpy as np

'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''

'\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n'

In [25]:
#Integer
np_int_array = np.array([1, 2, 3], dtype='i')
print(np_int_array)
print(np_int_array.dtype)

[1 2 3]
int32


In [26]:
#Boolean
np_boolean_array = np.array([True, False, True], dtype='b')
print(np_boolean_array)
print(np_boolean_array.dtype)

[1 0 1]
int8


In [27]:
#Unsigned Integer
np_unsigned_int_array = np.array([1, 2, 3], dtype=np.uint32)
print(np_unsigned_int_array)
print(np_unsigned_int_array.dtype)

[1 2 3]
uint32


In [28]:
#Float
np_float_array = np.array([1.1, 2.2, 3.3], dtype='f')
print(np_float_array)
print(np_float_array.dtype)

[1.1 2.2 3.3]
float32


In [29]:
#Complex Float
np_complex_float_array = np.array([1+2j, 3+4j], dtype='c')
print(np_complex_float_array)
print(np_complex_float_array.dtype)

[b'(' b'(']
|S1


In [30]:
#Timedelta
np_timeDelta_array = np.array([1, 2, 3], dtype='m')
print(np_timeDelta_array)
print(np_timeDelta_array.dtype)

[1 2 3]
timedelta64


In [31]:
#Datetime 
np_datetime_array = np.array(['2024-09-23', '2023-01-02'], dtype='M')
print(np_datetime_array)
print(np_datetime_array.dtype)

['2024-09-23' '2023-01-02']
datetime64[D]


In [32]:
#Object
np_object_array = np.array([1, 'apple', 3.14], dtype='O')
print(np_object_array)
print(np_object_array.dtype)

[1 'apple' 3.14]
object


In [33]:
#String
np_string_array = np.array([b'hello', b'world'], dtype='S')
print(np_string_array)
print(np_string_array.dtype)

[b'hello' b'world']
|S5


In [34]:
#Unicode String
np_unicode_string_array = np.array(['hello', 'world'], dtype='U')
print(np_unicode_string_array)
print(np_unicode_string_array.dtype)

['hello' 'world']
<U5


In [36]:
#Void
dt = np.dtype([('letter', 'S1'), ('number', 'i4')])

np_void_array = np.array([('x', 1), ('y', 2)], dtype=dt)
print(np_void_array)
print(np_void_array.dtype)

[(b'x', 1) (b'y', 2)]
[('letter', 'S1'), ('number', '<i4')]
