In [1]:
import numpy as np

In [2]:
# Filter elements greater than a value

arr = np.array(
    [1, 12, 13, 4, 5, 6, 7, 8, 9, 10, 2, 3]
)

# Filter elements greater than 5
filtered_arr = arr[arr > 5]

print('Filter elements greater than 5: ',filtered_arr)

Filter elements greater than 5:  [12 13  6  7  8  9 10]


In [3]:
#Filter elements that satisfy multiple conditions
arr = np.array(
    [1, 12, 13, 4, 5, 6, 7, 8, 9, 10, 2, 3]
)
filtered_arr = arr[(arr > 5) & (arr < 9)]
print('Filter elements that satisfy multiple conditions: ',filtered_arr)

Filter elements that satisfy multiple conditions:  [6 7 8]


In [4]:
#Filtering based on a condition using another array
arr = np.array([1, 12, 13, 4, 45, 6, 7, 8, 9, 10])  # 10 elements
arr2 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])  # 10 elements

# Filter elements in arr2 where corresponding elements in arr are greater than 5
filtered_arr2 = arr2[arr > 5]
print(filtered_arr2)

[ 20  30  50  60  70  80  90 100]


In [5]:
arr = np.array(
    [41, 42, 43, 44]
)

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = []

for element in arr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [7]:
#Boolean Mask
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_mask = [False, True, False, True, False, True, False]
newarr = arr[filter_mask]
print(newarr)

[2 4 6]


In [9]:
#Conditionals
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_mask = arr % 2 == 1
print(filter_mask)
newarr = arr[filter_mask]
print(newarr)

[ True False  True False  True False  True]
[1 3 5 7]


In [11]:
#Indices
indices=[0,2,4]
arr = np.array([1, 2, 3, 4, 5, 6, 7])
newarr = arr[indices]
print(newarr)

[1 3 5]


In [12]:
#Indices
arr = np.array([1, 2, 3, 4, 5, 6, 7])
indices = np.where(arr%2==1)
newarr = arr[indices]
print(newarr)

[1 3 5 7]


In [14]:
#Using custom filter method
def my_custom_filter(x):
    if x % 2 == 0:
        return True
    else:
        return False

arr = np.array([1, 2, 3, 4, 5, 6, 7])
filtered_arr = filter(my_custom_filter, arr)
print(np.array(list(filter_arr)))

[False  True False  True False  True False]
