In [1]:
import numpy as np

np_3d_array = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

print('3D Array: ', np_3d_array)

3D Array:  [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [2]:
#Access a specific slice
element = np_3d_array[1, :, :]
print('Accesses the 2nd 2D slice:: ', element)

Accesses the 2nd 2D slice::  [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [3]:
#Slicing along a specific axis:
element = np_3d_array[:, 1, :]
print('Accesses the second row from both 2D slices: ', element)

Accesses the second row from both 2D slices:  [[ 5  6  7  8]
 [17 18 19 20]]


In [4]:
np_5d_array = np.array([[[[[54, 82, 66, 74], [44, 91, 20, 32], [23, 78, 29, 83]],
                          [[1, 44, 27, 15], [49, 80, 1, 56], [84, 39, 9, 53]]],
                         [[[54, 37, 19, 59], [78, 85, 81, 50], [14, 85, 58, 74]],
                          [[3, 76, 82, 96], [68, 14, 25, 1], [55, 4, 30, 21]]]], [
                            [[[16, 39, 17, 60], [75, 95, 40, 11], [25, 86, 30, 29]],
                             [[33, 54, 78, 93], [24, 50, 22, 62], [74, 35, 38, 65]]],
                            [[[37, 58, 79, 31], [95, 22, 72, 82], [99, 36, 77, 21]],
                             [[75, 30, 11, 4], [16, 44, 83, 87], [26, 32, 13, 47]]]]])


In [5]:
# Slicing a 5D array (get all elements from the first two blocks)
slice_5d = np_5d_array[0, 1, 1, :, :]
print("Slice from 5D array:\n", slice_5d)

Slice from 5D array:
 [[ 3 76 82 96]
 [68 14 25  1]
 [55  4 30 21]]


In [6]:

#Find even elements from 5D Array
print('Find even elements from both rows: ', [np_5d_array[np_5d_array%2 == 0]])

Find even elements from both rows:  [array([54, 82, 66, 74, 44, 20, 32, 78, 44, 80, 56, 84, 54, 78, 50, 14, 58,
       74, 76, 82, 96, 68, 14,  4, 30, 16, 60, 40, 86, 30, 54, 78, 24, 50,
       22, 62, 74, 38, 58, 22, 72, 82, 36, 30,  4, 16, 44, 26, 32])]


In [7]:
print(np_5d_array[0,0,0,0, 1:4])

[82 66 74]
