In [46]:
import numpy as np

np_3d_array = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

print('3D Array: ', np_3d_array)

3D Array:  [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [47]:
#Access a specific element
# Accesses the element (1st block, 2nd row, 3rd column)
element = np_3d_array[0, 1, 2]  
print('Access a specific element: ',element)


Access a specific element:  7


In [48]:
#Using lists or arrays of indices
rows = [0, 1]  # Select rows 0 and 1
cols = [2, 1]  # Select columns 2 and 1
selected_elements = np_3d_array[rows, :, cols] 
print('Access specific elements using a list of indices: ', selected_elements)

Access specific elements using a list of indices:  [[ 3  7 11]
 [14 18 22]]


In [49]:
np_4d_array = np.array([
    [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
     [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]],
    
    [[[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]],
     [[37, 38, 39, 40], [41, 42, 43, 44], [45, 46, 47, 48]]]
])

# Accessing an element in the 4D array
element_4d = np_4d_array[1, 0, 2, 3]  # Access element 36 (2nd block, 1st sub-block, 3rd row, 4th column)
print("Element from 4D array:", element_4d)

Element from 4D array: 36


In [50]:
np_5d_array = np.array([[[[[54, 82, 66, 74], [44, 91, 20, 32], [23, 78, 29, 83]], [[1, 44, 27, 15], [49, 80, 1, 56], [84, 39, 9, 53]]], [[[54, 37, 19, 59], [78, 85, 81, 50], [14, 85, 58, 74]], [[3, 76, 82, 96], [68, 14, 25, 1], [55, 4, 30, 21]]]], [[[[16, 39, 17, 60], [75, 95, 40, 11], [25, 86, 30, 29]], [[33, 54, 78, 93], [24, 50, 22, 62], [74, 35, 38, 65]]], [[[37, 58, 79, 31], [95, 22, 72, 82], [99, 36, 77, 21]], [[75, 30, 11, 4], [16, 44, 83, 87], [26, 32, 13, 47]]]]])
# print(np_5d_array.tolist())

# Accessing an element in the 5D array
element_5d = np_5d_array[0, 1, 0, 1, 3]  # Access a specific element from the 5D array
print("Element from 5D array:", element_5d)

Element from 5D array: 50
