In [1]:
import numpy as np

In [2]:
"""unique - Unique Values"""
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_values = np.unique(arr)
print(unique_values)

[1 2 3 4 5]


In [3]:
"""argmax, argmin - Index of Max/Min Element"""
arr = np.array([10, 20, 30, 25, 15])
max_index = np.argmax(arr)
min_index = np.argmin(arr)
print(max_index)  
print(min_index)


2
0


In [4]:
"""arange - Creates Sequential NumPy Arrays"""
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [5]:
"""linspace - Creates Sequential NumPy Arrays with Linear Space"""
arr = np.linspace(0, 1, 5)
print(arr) 

[0.   0.25 0.5  0.75 1.  ]


In [6]:
"""split - Splits a NumPy Array into Different Arrays"""
arr = np.array([1, 2, 3, 4, 5, 6])
arr_split = np.split(arr, 3)
print(arr_split)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [7]:
"""dot - Dot Product of Two Arrays"""
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
dot_product = np.dot(arr1, arr2)
print(dot_product)

11


In [8]:
"""mean, median, std - Generate Statistical Values"""
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
median_value = np.median(arr)
std_deviation = np.std(arr)
print(mean_value) 
print(median_value)
print(std_deviation)

3.0
3.0
1.4142135623730951


In [9]:
"""concatenate - Concatenate Arrays (Check Axis)"""
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concatenated = np.concatenate((arr1, arr2), axis=0)
print(concatenated)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
"""vstack, hstack - Stack Arrays Vertically/Horizontally"""
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
vstacked = np.vstack((arr1, arr2))
hstacked = np.hstack((arr1, arr2))
print('vstacked: ',vstacked)
print('hstacked: ',hstacked)

vstacked:  [[1 2 3]
 [4 5 6]]
hstacked:  [1 2 3 4 5 6]


In [13]:
"""sum - Sum of Array Elements"""
arr = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(arr)
print(total_sum)

15
