In [1]:
import numpy as np

In [2]:
"""unique - Unique Values"""
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_values = np.unique(arr)
print(unique_values)

[1 2 3 4 5]


In [3]:
"""argmax, argmin - Index of Max/Min Element"""
arr = np.array([10, 20, 30, 25, 15])
max_index = np.argmax(arr)
min_index = np.argmin(arr)
print(max_index)  
print(min_index)


2
0


In [4]:
"""arange - Creates Sequential NumPy Arrays"""
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [5]:
"""linspace - Creates Sequential NumPy Arrays with Linear Space"""
arr = np.linspace(0, 1, 5)
print(arr) 

[0.   0.25 0.5  0.75 1.  ]


In [6]:
"""split - Splits a NumPy Array into Different Arrays"""
arr = np.array([1, 2, 3, 4, 5, 6])
arr_split = np.split(arr, 3)
print(arr_split)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [7]:
"""dot - Dot Product of Two Arrays"""
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
dot_product = np.dot(arr1, arr2)
print(dot_product)

11


In [8]:
"""mean, median, std - Generate Statistical Values"""
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
median_value = np.median(arr)
std_deviation = np.std(arr)
print(mean_value) 
print(median_value)
print(std_deviation)

3.0
3.0
1.4142135623730951


In [9]:
"""concatenate - Concatenate Arrays (Check Axis)"""
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concatenated = np.concatenate((arr1, arr2), axis=0)
print(concatenated)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
"""vstack, hstack - Stack Arrays Vertically/Horizontally"""
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
vstacked = np.vstack((arr1, arr2))
hstacked = np.hstack((arr1, arr2))
print('vstacked: ',vstacked)
print('hstacked: ',hstacked)

vstacked:  [[1 2 3]
 [4 5 6]]
hstacked:  [1 2 3 4 5 6]


In [11]:
"""sum - Sum of Array Elements"""
arr = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(arr)
print(total_sum)

15


In [12]:
"""Matrix Transpose"""
np_2d_array = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])
print(np_2d_array.transpose())

[[ 1 26]
 [ 2 27]
 [ 3 28]
 [ 4 29]
 [ 5 30]
 [ 6 31]
 [ 7 32]
 [ 8 33]
 [ 9 34]
 [10 35]
 [11 36]
 [12 37]
 [13 38]
 [14 39]
 [15 40]
 [16 41]
 [17 42]
 [18 43]
 [19 44]
 [20 45]
 [21 46]
 [22 47]
 [23 48]
 [24 49]
 [25 50]]


In [28]:
"""Random Suffle"""
# np.random.seed(42)
my_np_array = np.random.randint(5, size=(5,))
print(my_np_array)
np.random.shuffle(my_np_array)
print(my_np_array)

[0 0 2 2 1]
[0 0 2 1 2]


In [13]:
"""Matrix Transpose"""
np_2d_array = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])
print(np_2d_array.T)

[[ 1 26]
 [ 2 27]
 [ 3 28]
 [ 4 29]
 [ 5 30]
 [ 6 31]
 [ 7 32]
 [ 8 33]
 [ 9 34]
 [10 35]
 [11 36]
 [12 37]
 [13 38]
 [14 39]
 [15 40]
 [16 41]
 [17 42]
 [18 43]
 [19 44]
 [20 45]
 [21 46]
 [22 47]
 [23 48]
 [24 49]
 [25 50]]


In [29]:
data_set = np.random.rand(1000,5)
print("Data Set: \n",data_set)

Data Set: 
 [[0.09060643 0.61838601 0.38246199 0.98323089 0.46676289]
 [0.85994041 0.68030754 0.45049925 0.01326496 0.94220176]
 [0.56328822 0.3854165  0.01596625 0.23089383 0.24102547]
 ...
 [0.82767519 0.73986783 0.78902284 0.11910654 0.14054713]
 [0.28647374 0.51807717 0.74801608 0.83653089 0.70433532]
 [0.92859688 0.73874351 0.30626789 0.26508128 0.69619245]]


In [30]:
data_set[:5]

array([[0.09060643, 0.61838601, 0.38246199, 0.98323089, 0.46676289],
       [0.85994041, 0.68030754, 0.45049925, 0.01326496, 0.94220176],
       [0.56328822, 0.3854165 , 0.01596625, 0.23089383, 0.24102547],
       [0.68326352, 0.60999666, 0.83319491, 0.17336465, 0.39106061],
       [0.18223609, 0.75536141, 0.42515587, 0.20794166, 0.56770033]])

In [33]:
"""Split"""
index_1 = int(0.8 * len(data_set))
index_2 = int(0.9 * len(data_set))

trainset, valset, testset = np.split(
    data_set, [index_1, index_2]
)
print(len(trainset), len(valset), len(testset))



800 100 100
