In [2]:
import numpy as np

In [3]:
#Sorting a 1D Array

# Define a 1D array
arr_1d = np.array([12, 5, 7, 3, 19, 2, 9])

# Sort the array
sorted_arr_1d = np.sort(arr_1d)

print("Original 1D array:")
print(arr_1d)

print("\nSorted 1D array:")
print(sorted_arr_1d)


Original 1D array:
[12  5  7  3 19  2  9]

Sorted 1D array:
[ 2  3  5  7  9 12 19]


In [7]:
#Sorting a 2D Array Along Rows

# Define a 2D array
arr_2d = np.array([[12, 5, 7], [3, 19, 2], [9, 6, 10]])

# Sort each row
sorted_arr_2d_rows = np.sort(arr_2d, axis=1)

print("Original 2D array:")
print(arr_2d)

print("\n2D array sorted along rows:")
print(sorted_arr_2d_rows)

Original 2D array:
[[12  5  7]
 [ 3 19  2]
 [ 9  6 10]]

2D array sorted along rows:
[[ 5  7 12]
 [ 2  3 19]
 [ 6  9 10]]


In [5]:
#Sorting a 2D Array Along Columns

# Define a 2D array
arr_2d = np.array([[12, 5, 7], [3, 19, 2], [9, 6, 10]])

# Sort each column
sorted_arr_2d_columns = np.sort(arr_2d, axis=0)

print("Original 2D array:")
print(arr_2d)

print("\n2D array sorted along columns:")
print(sorted_arr_2d_columns)

Original 2D array:
[[12  5  7]
 [ 3 19  2]
 [ 9  6 10]]

2D array sorted along columns:
[[ 3  5  2]
 [ 9  6  7]
 [12 19 10]]


In [8]:
#Sorting a 1D Array in Descending Order
# Define a 1D array
arr_1d = np.array([12, 5, 7, 3, 19, 2, 9])

# Sort the array in descending order
sorted_arr_1d_desc = np.sort(arr_1d)[::-1]

print("1D array sorted in descending order:")
print(sorted_arr_1d_desc)

1D array sorted in descending order:
[19 12  9  7  5  3  2]
