In [40]:
import numpy as np
from holoviews.examples.gallery.apps.bokeh.game_of_life import shapes
from numpy import dtype
from statsmodels.sandbox.distributions.genpareto import shape

print(np.__version__)

1.26.4


In [41]:
my_np_array = np.array([1, 2, 3])
print(my_np_array)
print(my_np_array.dtype)
print(my_np_array.shape)
print(my_np_array.size)
print(my_np_array.ndim)

[1 2 3]
int32
(3,)
3
1


In [42]:
my_np_array2 = np.array([[1, 2, 3],[4,5,6]])
print(my_np_array2)
print(my_np_array2.dtype)
print(my_np_array2.shape)
print(my_np_array2.size)
print(my_np_array2.ndim)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)
6
2


In [43]:
np_my_array3=np.array([[1, 2],[4,5],[7,8]])
print(np_my_array3)
print(np_my_array3.dtype)
print(np_my_array3.shape)
print(np_my_array3.size)
print(np_my_array3.ndim)


[[1 2]
 [4 5]
 [7 8]]
int32
(3, 2)
6
2


In [44]:
np_my_array4 = np.array([1, 3, 5, 7, 2, 4, 6, 8])
#Slice from index 4 to end
print(np_my_array4[4:])
#Slice beganing to index 4
print(np_my_array4[:5])
#slice 
print(np_my_array4[-3:-1])

print(np_my_array4[1:5:2])

print(np_my_array4[::2])

print(np.reshape(np_my_array4,(4,2)))

[2 4 6 8]
[1 3 5 7 2]
[4 6]
[3 7]
[1 5 2 6]
[[1 3]
 [5 7]
 [2 4]
 [6 8]]


In [45]:
#Zeros shape
zeros_np_array = np.zeros(
    shape=(5,)
)
print(zeros_np_array)

[0. 0. 0. 0. 0.]


In [46]:
ones_np_array = np.ones(
    shape=(5,)
)
print(ones_np_array)

[1. 1. 1. 1. 1.]


In [47]:
assigned_with_specific_array = np.full(
    shape = (10,),
    fill_value = 20
)
print(assigned_with_specific_array)

[20 20 20 20 20 20 20 20 20 20]


In [54]:
identity_matrix = np.eye(
    4,
    dtype = int
)
print(identity_matrix.tolist())

[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]


In [49]:
my_empty_array = np.empty(
    shape = (5,)
)
print(my_empty_array)

[0. 0. 0. 0. 0.]


In [50]:
my_empty_array_int = my_empty_array.astype('int')
print(my_empty_array_int)
print(my_empty_array_int.dtype)


[0 0 0 0 0]
int32


In [51]:
np_2d_array = np.ones(
    shape = (10,4),
    dtype = int
)
print(np_2d_array)
print(np_2d_array.ndim)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
2


In [53]:
my_np_1d_array = np.array([1, 2, 3,4,5,6])
print(my_np_1d_array[2])
print(my_np_1d_array[-4])

3
3


In [60]:
np_2d_array = np.array(
    [
        [1, 2, 3, 4], 
        [5, 6, 7, 8], 
        [9, 10, 11, 12], 
        [11, 14, 15, 16]
     ]
)
np_2d_array
# print(np_2d_array)

print(np_2d_array[1:4, 1:3])

[[ 6  7]
 [10 11]
 [14 15]]


In [52]:
#Type Casting
#Using astype() method


