In [1]:
import numpy as np

In [3]:
#Using astype() method
arr = np.array(
    [1.5, 2.8, 3.2]
)
print('Before casting the data type: ', arr.dtype)
int_arr = arr.astype(int)  # Cast to integer
print('Int Array: ',int_arr)
print('After casting the data type:', int_arr.dtype)

Before casting the data type:  float64
Int Array:  [1 2 3]
After casting the data type: int32


In [4]:
#Specifying dtype during array creation
arr = np.array(
    [1.5, 2.8, 3.2], 
    dtype=int # Creates an integer array
)  
print('Array: ',arr)
print('Data Type: ',arr.dtype)

Array:  [1 2 3]
Data Type:  int32


In [7]:
#Using numpy.cast module
arr = np.array([1.5, 2, 3.2, 5, 6.6, 8])

# Cast to integer
int_arr = np.int_(arr)
print('Cast to integer: ', int_arr)

# Cast to float
float_arr = np.float_(arr)
print('Cast to float: ', float_arr)


Cast to integer:  [1 2 3 5 6 8]
Cast to float:  [1.5 2.  3.2 5.  6.6 8. ]


In [9]:
#Casting with scalar conversion
scalar = 3.14159
scalar2 = 8
# Convert scalar to integer
int_scalar = np.int64(scalar)
print('Convert scalar to integer: ',int_scalar)

# Convert scalar to float
float_scalar = np.float32(scalar2)
print('Convert scalar to float: ',float_scalar)


Convert scalar to integer:  3
Convert scalar to float:  8.0


In [10]:
#Casting during arithmetic operations
arr1 = np.array(
    [1, 2, 3], 
    dtype=np.int32
)

arr2 = np.array(
    [1.1, 2.2, 3.3], 
    dtype=np.float64
)

# The integer array will be cast to float64
result = arr1 + arr2
print('Result: ',result)
print('Data Type: ',result.dtype)


[2.1 4.2 6.3]
float64


In [12]:
#Casting using numpy.ndarray.view()
arr = np.array(
    [1, 2, 3, 4],
    dtype=np.int32
)

print("Original array:")
print(arr)
print(arr.dtype)  # The array is of type int32

# View the array as 32-bit floats (without changing the data)
float_view = arr.view(np.float32)
print("\nArray viewed as float32:")
print(float_view)
print(float_view.dtype)


Original array:
[1 2 3 4]
int32

Array viewed as float32:
[1.e-45 3.e-45 4.e-45 6.e-45]
float32


In [15]:
#Casting using numpy.ndarray.astype() with safety controls
arr = np.array(
    [1, 2, 3]
)

# Cast to float with a 'safe' cast
float_arr = arr.astype('int')
print('Cast to float with a safe cast: ',float_arr)
print('Data Type: ',float_arr.dtype)


Cast to float with a safe cast:  [1 2 3]
Data Type:  int32
