In [1]:
import numpy as np

In [ ]:
"""Vectorization"""

In [2]:
"""Element-wise multiplication"""
array = np.array([1, 2, 3, 4, 5])
result = array * 2
print(result)  # Output: [ 2,  4,  6,  8, 10]

[ 2  4  6  8 10]


In [3]:
"""Matrix multiplication"""
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result = np.dot(array1, array2)
print(result)
# Output:
# [[19 22],
#  [43 50]]

[[19 22]
 [43 50]]


In [ ]:
"""Broadcasting"""

In [23]:
arr1 = np.array([1, 2, 3])         # Shape (3,)
arr2 = np.array([[10], [20], [30]]) # Shape (3, 1)

# Broadcasting occurs here
result = arr1 + arr2

print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

# Broadcasting occurs here
result = arr + scalar

print(result)

[[11 12 13]
 [14 15 16]]


In [22]:
array1 = np.array([1, 2, 3])
array2 = np.array([[4, 5, 6]])
result = array1 * array2
result

array([[ 4, 10, 18]])

In [25]:
array1 = np.array([1, 2, 3])
array2 = np.array([[4], [5], [6]])
result = array1 + array2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [26]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[[5, 6], [7, 8]]])
result = array1 + array2
print(result)

[[[ 6  8]
  [10 12]]]


In [28]:
scalar = 5
array = np.array([1, 2, 3])
result = scalar * array
result

array([ 5, 10, 15])

In [29]:
array1 = np.array([1, 2, 3])
array2 = np.array([[4], [5], [6]])
result = array1 * array2
print(result)

[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [30]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[[5, 6], [7, 8]]])
result = array1 * array2
print(result)

[[[ 5 12]
  [21 32]]]
